#include $(src)/Kbuild-mtk-custom-env

curr := platform/mtk_platform_common

mali_kbase-y += $(curr)/mtk_platform_common.o

ifeq ($(CONFIG_MALI_MTK_LOG_BUFFER),y)
    mali_kbase-y += $(curr)/mtk_platform_logbuffer.o
endif ## CONFIG_MALI_MTK_LOG_BUFFER ##

ccflags-y += -I$(srctree)/drivers/devfreq/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/perf_common/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/tinysys_scmi/
ccflags-y += -Wno-unused-variable -Wno-unused-function

ifeq ($(CONFIG_MALI_MTK_DEBUG_DUMP),y)
    mali_kbase-y += $(curr)/mtk_platform_debug_dump_csg.o
    mali_kbase-y += $(curr)/mtk_platform_debug_dump_cpu.o
    mali_kbase-y += $(curr)/mtk_platform_debug_dump_kcpu.o
    mali_kbase-y += $(curr)/mtk_platform_debug_dump_gpu.o
    mali_kbase-y += $(curr)/mtk_platform_debug_dump_gpu_debugfs.o
endif ## CONFIG_MALI_MTK_DEBUG_DUMP ##