include $(src)/Kbuild-mtk-custom-env

curr := platform/mtk_platform_common

mali_kbase-y += $(curr)/mtk_platform_common.o
mali_kbase-y += $(curr)/mtk_platform_debug.o

ifeq ($(CONFIG_MALI_MTK_DEVFREQ),y)
mali_kbase-y += $(curr)/mtk_gpu_dvfs.o
mali_kbase-y += $(curr)/mtk_gpu_devfreq_governor.o
endif
ccflags-y += -I$(srctree)/drivers/devfreq/

