export MTK_PLATFORM_VERSION := mt6789

obj-m += mali_avalon/a16w_jm/drivers/gpu/arm/midgard/
obj-m += mali_avalon/a16w_jm/drivers/base/arm/memory_group_manager/
obj-m += mali_avalon/a16w_jm/drivers/base/arm/protected_memory_allocator/
obj-m += mali_avalon/a16w_jm/drivers/base/arm/dma_buf_test_exporter/
