################################################################################
#@Copyright      Copyright (c) Imagination Technologies Ltd. All Rights Reserved
#@License        Strictly Confidential.
################################################################################

load("@bazel_skylib//lib:collections.bzl", "collections")
load("@bazel_skylib//rules:common_settings.bzl", "string_flag")
load("//build/bazel_mgk_rules:mgk_ddk_ko.bzl", "define_mgk_ddk_ko")
load(":flags.bzl","COPTS_MTK")
load("@mgk_info//:kernel_version.bzl", "kernel_version")
load(
	"@rules_pkg//pkg:mappings.bzl",
	"pkg_files",
)
load("@mgk_info//:dict.bzl","DEFCONFIG_OVERLAYS")
#load("@rules_pkg//pkg:install.bzl", "pkg_install")
load(
	"@kleaf//build/kernel/kleaf:kernel.bzl", "ddk_headers", "ddk_module", "kernel_module_group",
)
load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")
load(":pvr_config_setting.bzl", "generate_config_setting_bool",
								"generate_config_setting_string",
								"generate_config_setting_multiple_string")

package(default_visibility = ["//visibility:public"])

# TODO
#load("@kleaf//build/kernel/kleaf:kernel.bzl", "checkpatch", "kernel_module")
#checkpatch(
#    name = "checkpatch",
#    checkpatch_pl = "//common:scripts/checkpatch.pl",
#)
#


filegroup(
	name = "config_kernel_h",
	srcs = [
		"//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/include:config_kernel_secure_mt6855.h"
	] if "gpu_protect.config" in DEFCONFIG_OVERLAYS else [
		"//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/include:config_kernel_user_mt6855.h"
	],
	visibility = ["//visibility:public"],
)

# It reads tunable coonfigurations from intermediate files, config_kernel.mk and
# config_kernel.h, generated by '$ make config'.
# It translates IMG tunable configurations in Makefile to Bazel configurations.
# Same combinations of configurations from Makefile and Bazel should compile
# same files.

# For sources files that are separated by configurations, they may be located by
# by rogue and volcanic,... , and some common files. By naminbg, if seeing
# 'common' as suffix to the sources,
# ex 'FILES_SUPPORT_FALLBACK_FENCE_SYNC_common', it indicates there are other
# parts of source files located under path/to/rogue|volcanic, etc..., and
# defined in BUILD.bazel in that path.


# Illustration of generate_config_setting_bool(...):
# Exampl of config PDUMP:
# It creates config_setting of
#   cs_PDUMP
# and bool_flag PDUMP
# if PDUMP is 1, cs_PVR_HANDLE_BACKEND_generic is enable
# The value can be modified in .bazelrc
#
default_empty=""
generate_config_setting_bool("cs_PDUMP", "PDUMP", enable_value="True", default_value=False)
generate_config_setting_bool("cs_SUPPORT_RGX", "SUPPORT_RGX", enable_value="True", default_value=True)
generate_config_setting_bool("cs_PVRSRV_ENABLE_LINUX_MMAP_STATS", "PVRSRV_ENABLE_LINUX_MMAP_STATS", enable_value="True", default_value=False)
generate_config_setting_bool("cs_PVRSRV_ENABLE_GPU_MEMORY_INFO", "PVRSRV_ENABLE_GPU_MEMORY_INFO", enable_value="True", default_value=False)
generate_config_setting_bool("cs_SUPPORT_NATIVE_FENCE_SYNC", "SUPPORT_NATIVE_FENCE_SYNC", enable_value="True", default_value=False)
generate_config_setting_bool("cs_SUPPORT_FALLBACK_FENCE_SYNC", "SUPPORT_FALLBACK_FENCE_SYNC", enable_value="True", default_value=False)
generate_config_setting_bool("cs_USE_PVRSYNC_DEVNODE", "USE_PVRSYNC_DEVNODE", enable_value="True", default_value=False)
generate_config_setting_bool("cs_SUPPORT_BUFFER_SYNC", "SUPPORT_BUFFER_SYNC", enable_value="True", default_value=False)
generate_config_setting_bool("cs_SUPPORT_LINUX_DVFS", "SUPPORT_LINUX_DVFS", enable_value="True", default_value=False)
generate_config_setting_bool("cs_PVRSRV_ENABLE_PVR_ION_STATS", "PVRSRV_ENABLE_PVR_ION_STATS", enable_value="True", default_value=False)
generate_config_setting_bool("cs_PVRSRV_TRACE_ROGUE_EVENTS", "PVRSRV_TRACE_ROGUE_EVENTS", enable_value="True", default_value=True)
generate_config_setting_bool("cs_PVRSRV_ANDROID_TRACE_GPU_WORK_PERIOD", "PVRSRV_ANDROID_TRACE_GPU_WORK_PERIOD", enable_value="True", default_value=True)
generate_config_setting_bool("cs_SUPPORT_USC_BREAKPOINT", "SUPPORT_USC_BREAKPOINT", enable_value="True", default_value=True)
generate_config_setting_bool("cs_SUPPORT_VALIDATION", "SUPPORT_VALIDATION", enable_value="True", default_value=False)
generate_config_setting_bool("cs_PVR_TESTING_UTILS", "PVR_TESTING_UTILS", enable_value="True", default_value=False)
generate_config_setting_bool("cs_PVRSRV_ANDROID_TRACE_GPU_FREQ", "PVRSRV_ANDROID_TRACE_GPU_FREQ", enable_value="True", default_value=False)
generate_config_setting_bool("cs_SUPPORT_PDVFS", "SUPPORT_PDVFS", enable_value="True", default_value=False)
generate_config_setting_bool("cs_SUPPORT_PHYSMEM_TEST", "SUPPORT_PHYSMEM_TEST", enable_value="True", default_value=False)
generate_config_setting_bool("cs_SUPPORT_SECURE_EXPORT", "SUPPORT_SECURE_EXPORT", enable_value="True", default_value=True)
generate_config_setting_bool("cs_SUPPORT_WRAP_EXTMEM", "SUPPORT_WRAP_EXTMEM", enable_value="True", default_value=True)
generate_config_setting_bool("cs_SUPPORT_RGXKICKSYNC_BRIDGE", "SUPPORT_RGXKICKSYNC_BRIDGE", enable_value="True", default_value=True)
generate_config_setting_bool("cs_PVRSRV_ENABLE_HTB", "PVRSRV_ENABLE_HTB", enable_value="True", default_value=False)
generate_config_setting_bool("cs_SUPPORT_DMA_TRANSFER", "SUPPORT_DMA_TRANSFER", enable_value="True", default_value=False)
generate_config_setting_bool("cs_PVRSRV_ENABLE_DYNAMIC_PHYSHEAPS", "PVRSRV_ENABLE_DYNAMIC_PHYSHEAPS", enable_value="True", default_value=False)
generate_config_setting_bool("cs_SUPPORT_WORKLOAD_ESTIMATION", "SUPPORT_WORKLOAD_ESTIMATION", enable_value="True", default_value=False)
generate_config_setting_bool("cs_SUPPORT_DMA_HEAP", "SUPPORT_DMA_HEAP", enable_value="True", default_value=True)
generate_config_setting_bool("cs_SUPPORT_ION", "SUPPORT_ION", enable_value="True", default_value=False)
generate_config_setting_bool("cs_SUPPORT_APOLLO_FPGA", "SUPPORT_APOLLO_FPGA", enable_value="True", default_value=False)
# Currently not in used in bazel
# generate_config_setting_bool("cs_SUPPORT_LINUX_WRAP_EXTMEM_PAGE_TABLE_WALK", "SUPPORT_LINUX_WRAP_EXTMEM_PAGE_TABLE_WALK", enable_value="True", default_value=False)
# generate_config_setting_bool("cs_HOST_PRIMARY_ARCH", "HOST_PRIMARY_ARCH", enable_value="True", default_value=True)


# Illustration of generate_config_setting_multiple_string(...):
# Example of config PVR_HANDLE_BACKEND:
# It creates config_setting of
#   cs_PVR_HANDLE_BACKEND_generic
#   cs_PVR_HANDLE_BACKEND_idr
# and string_flag PVR_HANDLE_BACKEND.
# if PVR_HANDLE_BACKEND is generic, cs_PVR_HANDLE_BACKEND_generic is enable
# if PVR_HANDLE_BACKEND is idr, cs_PVR_HANDLE_BACKEND_idr is enable
# The value can be modified in .bazelrc
#
generate_config_setting_multiple_string("cs_PVR_HANDLE_BACKEND", "PVR_HANDLE_BACKEND",  default_empty, available_values=["generic", "idr", ""])
# cs_PVR_ARCH_rogue, cs_PVR_ARCH_volcanic
generate_config_setting_multiple_string("cs_PVR_ARCH", "PVR_ARCH",  default_empty, available_values=["rogue", "volcanic", ""])
# cs_PVRSRV_DIR_services
generate_config_setting_multiple_string("cs_PVRSRV_DIR", "PVRSRV_DIR",  default_empty, available_values=["services", ""])
generate_config_setting_multiple_string("cs_PVR_SYSTEM", "PVR_SYSTEM",  default_empty, available_values=["rgx_linux_tc", "mt8173", ""])
generate_config_setting_string("cs_PVRSRV_PHYSMEM_CPUMAP_HISTORY", "PVRSRV_PHYSMEM_CPUMAP_HISTORY", "1", default_empty, available_values=["0", "1", ""])


#config_setting(
#    name = "cs_PVR_ARCH_volcanic_and_SUPPORT_WORKLOAD_ESTIMATION",
#    flag_values = {":PVR_ARCH": "volcanic",
##    			   ":SUPPORT_WORKLOAD_ESTIMATION": "1"},
#)

FILES_SUPPORT_RGX = [
    "services/server/devices/rgx_bridge_init.c",
    "services/server/devices/rgxfwdbg.c",
    "services/server/devices/rgxtimerquery.c",
    "services/server/devices/rgxccb.c",
    "services/server/devices/rgxdebug_common.c",
    "services/server/devices/rgxfwtrace_strings.c",
    "services/server/devices/rgxfwcmnctx.c",
    "services/server/devices/rgxfwriscv.c",
    "services/server/devices/rgxbvnc.c",
    "services/server/devices/rgxlayer_impl_common.c",
    "services/server/devices/rgxmem.c",
    "services/server/devices/rgxmmuinit.c",
    "services/server/devices/rgxregconfig.c",
    "services/server/devices/rgxsyncutils.c",
    "services/server/devices/rgxtdmtransfer.c",
    "services/server/devices/rgxutils.c",
    "services/server/devices/rgxhwperf_common.c",
    "services/server/devices/rgxpower.c",
    "services/server/devices/rgxtimecorr.c",
    "services/server/devices/rgxcompute.c",
    "services/server/devices/rgxshader.c",
    "services/server/devices/rgxfwutils.c",
    ]

FILES_PDUMP_common = [
    "services/server/common/pdump_server.c",
    "services/server/common/pdump_mmu.c",
    "services/server/common/pdump_physmem.c",
    "services/shared/common/devicemem_pdump.c",
    "services/shared/common/devicememx_pdump.c",
]
filegroup(
	name = "fg_PDUMP",
    srcs = select({
		":cs_PDUMP_and_PVR_ARCH_VOLCANIC" : FILES_PDUMP_common,
		":cs_PDUMP_and_PVR_ARCH_ROGUE" : FILES_PDUMP_common,
		# It is not allowed to have empty srcs, use img_defs.h as dummy file,
		# which is always included.
		"//conditions:default": ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/include:fg_dummy"],
    })
)

FILES_PDUMP_and_SUPPORT_RGX_common = [
    "services/server/devices/rgxpdump_common.c",
]
filegroup(
	name = "fg_PDUMP_and_SUPPORT_RGX_common",
    srcs = select({
		":cs_PDUMP_and_SUPPORT_RGX" : FILES_PDUMP_and_SUPPORT_RGX_common,
		"//conditions:default": ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/include:fg_dummy"],
    })
)

FILES_SUPPORT_NATIVE_FENCE_SYNC = [
    "services/server/env/linux/pvr_sync_ioctl_common.c",
    "services/server/env/linux/pvr_sync_file.c",
    "services/server/env/linux/pvr_counting_timeline.c",
    "services/server/env/linux/pvr_sw_fence.c",
    "services/server/env/linux/pvr_export_fence.c",
    "services/server/env/linux/pvr_fence.c",
]

FILES_SUPPORT_FALLBACK_FENCE_SYNC_common = [
    "services/server/common/sync_fallback_server.c",
    #"services/server/env/linux/ossecure_export.c",
]
filegroup(
	name = "fg_SUPPORT_FENCE_SYNC",
   	srcs = select({
		":cs_SUPPORT_NATIVE_FENCE_SYNC" : FILES_SUPPORT_NATIVE_FENCE_SYNC,
		":cs_SUPPORT_FALLBACK_FENCE_SYNC" : FILES_SUPPORT_FALLBACK_FENCE_SYNC_common,
#		":cs_SUPPORT_FALLBACK_FENCE_SYNC_rogue" : FILES_SUPPORT_FALLBACK_FENCE_SYNC_common,
#        "//conditions:default": ["include/img_defs.h"],

		"//conditions:default": ["services/server/env/linux/pvr_sync_ioctl_common.c",
								"services/server/env/linux/pvr_sync_file.c",
								"services/server/env/linux/pvr_counting_timeline.c",
								"services/server/env/linux/pvr_sw_fence.c",
								"services/server/env/linux/pvr_export_fence.c",
								"services/server/env/linux/pvr_fence.c",],
    })
)

# PVRSRV_ENABLE_GPU_MEMORY_INFO
FILES_PVRSRV_ENABLE_GPU_MEMORY_INFO_common = [
    "services/server/common/ri_server.c",
]
filegroup(
	name = "fg_PVRSRV_ENABLE_GPU_MEMORY_INFO",
    srcs = select({
		":cs_PVRSRV_ENABLE_GPU_MEMORY_INFO" : FILES_PVRSRV_ENABLE_GPU_MEMORY_INFO_common,
		"//conditions:default": ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/include:fg_dummy"],
    })
)


# SUPPORT_RGX & PVR_ARCH
FILES_SUPPORT_RGX_and_PVR_ARCH_rogue = [
    "services/shared/devices/rogue/rgx_hwperf_table.c", # -> rogue specific
]
FILES_SUPPORT_RGX_and_PVR_ARCH_common = [
    "services/server/devices/rgxfwimageutils.c",
]
FILES_SUPPORT_RGX_and_PVR_ARCH_ALL = FILES_SUPPORT_RGX_and_PVR_ARCH_common +  FILES_SUPPORT_RGX_and_PVR_ARCH_rogue
config_setting(
    name = "cs_SUPPORT_RGX_and_PVR_ARCH_VOLCANIC",
    flag_values = {":SUPPORT_RGX": "1",
    			   ":PVR_ARCH": "volcanic"},
)
config_setting(
    name = "cs_SUPPORT_RGX_and_PVR_ARCH_ROGUE",
    flag_values = {":SUPPORT_RGX": "1",
    			   ":PVR_ARCH": "rogue"},
)
filegroup(
	name = "fg_SUPPORT_RGX_and_PVR_ARCH",
    srcs = select({
		":cs_SUPPORT_RGX_and_PVR_ARCH_VOLCANIC" : FILES_SUPPORT_RGX_and_PVR_ARCH_common,
		":cs_SUPPORT_RGX_and_PVR_ARCH_ROGUE" : FILES_SUPPORT_RGX_and_PVR_ARCH_rogue + FILES_SUPPORT_RGX_and_PVR_ARCH_common,
#        "//conditions:default": ["include/img_defs.h"],
		"//conditions:default": ["services/server/devices/rgxfwimageutils.c"],
    })
)

# SUPPORT_LINUX_DVFS
FILES_SUPPORT_LINUX_DVFS = [
    "services/server/env/linux/pvr_dvfs_device.c",
    "services/server/env/linux/pvr_dvfs_common.c",
]

# SUPPORT_PDVFS
FILES_SUPPORT_PDVFS = [
    "services/server/env/linux/pvr_dvfs_proactive.c",
    "services/server/env/linux/pvr_dvfs_common.c",
]

# PVRSRV_ENABLE_HTB
FILES_PVRSRV_ENABLE_HTB_common = [
    "services/shared/common/htbuffer.c",
    "services/server/common/htbserver.c",
    "services/server/common/htb_debug.c",
]
filegroup(
	name = "fg_PVRSRV_ENABLE_HTB",
    srcs = select({
		":cs_PVRSRV_ENABLE_HTB" : FILES_PVRSRV_ENABLE_HTB_common,
		"//conditions:default": ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/include:fg_dummy"],
    })
)

# SUPPORT_WRAP_EXTMEM
FILES_SUPPORT_WRAP_EXTMEM = [
    "services/server/env/linux/physmem_extmem_linux.c",
    "services/server/common/physmem_extmem.c"
]
FILES_PVRSRV_ENABLE_DYNAMIC_PHYSHEAPS = [
    "services/server/common/physmem_dlm.c",
    "services/server/common/physmem_ima.c"
]

# SUPPORT_DMA_TRANSFER
FILES_SUPPORT_DMA_TRANSFER_rogue = [
    "generated/rogue/dma_bridge/server_dma_bridge.c",
]
FILES_SUPPORT_DMA_TRANSFER_common = ["services/server/common/dma_km.c"]
filegroup(
	name = "fg_SUPPORT_DMA_TRANSFER",
    srcs = select({
		":cs_SUPPORT_DMA_TRANSFER" : FILES_SUPPORT_DMA_TRANSFER_common,
		"//conditions:default": ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/include:fg_dummy"],
    })
)

# Multiple 'and' configurations

config_setting(
    name = "cs_PDUMP_and_PVR_ARCH_VOLCANIC",
    flag_values = {":PDUMP": "1",
    			   ":PVR_ARCH": "volcanic"},
)

config_setting(
    name = "cs_PDUMP_and_PVR_ARCH_ROGUE",
    flag_values = {":PDUMP": "1",
    			   ":PVR_ARCH": "rogue"},
)

config_setting(
    name = "cs_PDUMP_and_SUPPORT_RGX",
    flag_values = {":PDUMP": "1",
    			   ":SUPPORT_RGX": "1"},
)

config_setting(
    name = "cs_SUPPORT_RGX_and_PVRSRV_TRACE_ROGUE_EVENTS",
    flag_values = {":SUPPORT_RGX": "1",
				   ":PVRSRV_TRACE_ROGUE_EVENTS": "1"},
)

config_setting(
    name = "cs_SUPPORT_RGX_and_PVRSRV_ANDROID_TRACE_GPU_WORK_PERIOD",
    flag_values = {":SUPPORT_RGX": "1",
				   ":PVRSRV_ANDROID_TRACE_GPU_WORK_PERIOD": "1"},
)

config_setting(
    name = "cs_SUPPORT_RGX_and_SUPPORT_USC_BREAKPOINT",
    flag_values = {":SUPPORT_RGX": "1",
    			   ":SUPPORT_USC_BREAKPOINT": "1"},
)

config_setting(
    name = "cs_SUPPORT_VALIDATION_and_PVR_TESTING_UTILS",
    flag_values = {":SUPPORT_VALIDATION": "1",
    			   ":PVR_TESTING_UTILS": "1"},
)

config_setting(
    name = "cs_SUPPORT_RGX_and_SUPPORT_PDVFS",
    flag_values = {":SUPPORT_RGX": "1",
    			   ":SUPPORT_PDVFS": "1" },
)

config_setting(
    name = "cs_SUPPORT_RGX_and_SUPPORT_RGXKICKSYNC_BRIDGE",
    flag_values = {":SUPPORT_RGXKICKSYNC_BRIDGE": "1",
    			   ":SUPPORT_RGX": "1"},
)

config_setting(
    name = "cs_SUPPORT_RGX_and_SUPPORT_WORKLOAD_ESTIMATION",
    flag_values = {":SUPPORT_RGX": "1",
    			   ":SUPPORT_WORKLOAD_ESTIMATION": "1"},
)
config_setting(
    name = "cs_PVR_ARCH_volcanic_and_PVR_SYSTEM_rgx_linux_tc",
    flag_values = { ":PVR_ARCH": "volcanic",
					":PVR_SYSTEM": "rgx_linux_tc"
		  },
)
config_setting(
    name = "cs_PVR_ARCH_rogue_and_PVR_SYSTEM_rgx_linux_tc",
    flag_values = { ":PVR_ARCH": "rogue",
					":PVR_SYSTEM": "rgx_linux_tc"
		  },
)
config_setting(
    name = "cs_PVR_ARCH_volcanic_and_PVR_SYSTEM_mt8173",
    flag_values = { ":PVR_ARCH": "volcanic",
					":PVR_SYSTEM": "mt8173"
		  },
)
config_setting(
    name = "cs_PVR_ARCH_rogue_and_PVR_SYSTEM_mt8173",
    flag_values = { ":PVR_ARCH": "rogue",
					":PVR_SYSTEM": "mt8173"
		  },
)

# PVR_SYSTEM
filegroup(
	name = "fg_PVR_SYSTEM",
	srcs = select({
		":cs_PVR_ARCH_volcanic_and_PVR_SYSTEM_rgx_linux_tc":  ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/system/volcanic:rgx_linux_tc_sources"],
		":cs_PVR_ARCH_rogue_and_PVR_SYSTEM_rgx_linux_tc":  ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/system/rogue:rgx_linux_tc_sources"],
#        "//conditions:default": ["include/img_defs.h"],
        "//conditions:default": ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/system/volcanic:rgx_linux_tc_sources"],

	}),
)


define_mgk_ddk_ko(
	name = "pvrsrvkm",
    srcs = glob([
			"services/**",
			"services/include/**",
			"**/*.h",
    	  ],
			exclude =
                      FILES_SUPPORT_RGX +
					  FILES_PDUMP_common +
                      FILES_SUPPORT_NATIVE_FENCE_SYNC +
                      FILES_SUPPORT_FALLBACK_FENCE_SYNC_common +
                      FILES_PVRSRV_ENABLE_GPU_MEMORY_INFO_common +
                      FILES_PDUMP_and_SUPPORT_RGX_common +
                      FILES_SUPPORT_RGX_and_PVR_ARCH_ALL +
                      FILES_SUPPORT_LINUX_DVFS +
                      FILES_SUPPORT_PDVFS +
                      FILES_PVRSRV_ENABLE_HTB_common +
                      FILES_SUPPORT_WRAP_EXTMEM +
                      FILES_PVRSRV_ENABLE_DYNAMIC_PHYSHEAPS +
                      FILES_SUPPORT_DMA_TRANSFER_common +

                    [
						"**/*.mk",
						"services/server/env/linux/physmem_test.c",
						"services/server/env/linux/pvr_gputrace.c",
						# SUPPORT_RGX && PVRSRV_ANDROID_TRACE_GPU_FREQ
						"services/server/env/linux/pvr_gpufreq.c",
						# SUPPORT_RGX && UPPORT_RGXKICKSYNC_BRIDGE
						"services/server/devices/rgxkicksync.c",
						# SUPPORT_RGX_and_SUPPORT_USC_BREAKPOINT
						"services/server/devices/rgxbreakpoint.c",
						# SUPPORT_PDVFS
						"services/server/devices/rgxpdvfs.c",
                        # cs_SUPPORT_WORKLOAD_ESTIMATION
						"services/server/devices/rgxworkest.c",
						# cs_SUPPORT_VALIDATION_and_PVR_TESTING_UTILS
						"services/server/devices/rgxgpumap.c",
						# cs_PVR_TESTING_UTILS
						"services/server/common/tutils.c",
						# cs_SUPPORT_SECURE_EXPORT
						#"services/server/env/linux/ossecure_export.c",
						# cs_PVRSRV_PHYSMEM_CPUMAP_HISTORY
						"services/server/common/physmem_cpumap_history.c",
						# cs_PVR_HANDLE_BACKEND_generic
						"services/server/common/handle_generic.c",
						# cs_PVR_HANDLE_BACKEND_idr
						"services/server/env/linux/handle_idr.c",
						# cs_PVRSRV_ENABLE_LINUX_MMAP_STATS
						"services/server/env/linux/mmap_stats.c",
						# cs_SUPPORT_NATIVE_FENCE_SYNC
						# cs_SUPPORT_FALLBACK_FENCE_SYNC
						# cs_USE_PVRSYNC_DEVNODE
						"services/server/env/linux/pvr_sync_ioctl_dev.c",
						"services/server/env/linux/pvr_sync_ioctl_drm.c",
						# cs_SUPPORT_BUFFER_SYNC
						"services/server/env/linux/pvr_buffer_sync.c",
						# CONFIG_PROC_FS
						"services/server/env/linux/pvr_procfs.c",
						# CONFIG_DEBUG_FS
						"services/server/env/linux/pvr_debugfs.c",

						# cs_PVRSRV_ENABLE_PVR_ION_STATS
						"services/server/env/linux/pvr_ion_stats.c",
						#
						"services/server/devices",
						"services/system/rgx_nohw/**",
						"services/server/env/linux/osfunc_arm.c",
						"services/server/env/linux/osfunc_arm64.c",
						"services/server/env/linux/osfunc_riscv.c",
						"services/server/env/linux/osfunc_mips.c",
						"services/server/env/linux/osfunc_metag.c",
						# CONFIG_PCI
						"services/system/common/env/linux/pci_support.c",
			],
		) + [ ":config_kernel_h",
			]
		+ [":fg_PDUMP"]
		+ [":fg_SUPPORT_FENCE_SYNC"]
		+ [":fg_PVRSRV_ENABLE_GPU_MEMORY_INFO"]
		+ [":fg_SUPPORT_RGX_and_PVR_ARCH"]
		+ [":fg_SUPPORT_DMA_TRANSFER"]
		+ [":fg_PVR_SYSTEM"]
		+ [":fg_PDUMP_and_SUPPORT_RGX_common"]
		+ [":fg_PVRSRV_ENABLE_HTB"]
		+ select ({
			":cs_PVR_ARCH_volcanic": ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/generated/volcanic:generated_sources"]
								   + ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/server/devices/volcanic:device_sources"],
			":cs_PVR_ARCH_rogue": ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/generated/rogue:generated_sources"]
							    + ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/server/devices/rogue:device_sources"],
			"//conditions:default": ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/generated/volcanic:generated_sources"]
								   + ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/server/devices/volcanic:device_sources"],
		})
		+ select({
			":cs_PVRSRV_ENABLE_PVR_ION_STATS": ["services/server/env/linux/pvr_ion_stats.c"],
			"//conditions:default": [],
		})
		+ select({
			":cs_SUPPORT_LINUX_DVFS": FILES_SUPPORT_LINUX_DVFS,
			":cs_SUPPORT_PDVFS": FILES_SUPPORT_PDVFS,
			"//conditions:default": [],
		})
		+ select({
			":cs_SUPPORT_BUFFER_SYNC": ["services/server/env/linux/pvr_buffer_sync.c"],
			"//conditions:default": [],
		})
		+ select({
			":cs_USE_PVRSYNC_DEVNODE": ["services/server/env/linux/pvr_sync_ioctl_dev.c"],
			"//conditions:default": ["services/server/env/linux/pvr_sync_ioctl_dev.c"],
		})
		+ select({
			":cs_PVRSRV_ENABLE_LINUX_MMAP_STATS": ["services/server/env/linux/mmap_stats.c"],
			"//conditions:default": [],
		})
		+ select({
			":cs_PVR_HANDLE_BACKEND_generic": ["services/server/common/handle_generic.c"],
			"//conditions:default": [],
		})
		+ select({
			":cs_PVR_HANDLE_BACKEND_idr": ["services/server/env/linux/handle_idr.c"],
			"//conditions:default": ["services/server/env/linux/handle_idr.c"],
		})
		+ select({
			":cs_PVRSRV_PHYSMEM_CPUMAP_HISTORY": ["services/server/common/physmem_cpumap_history.c"],
			"//conditions:default": [],
		})
		+ select({
			":cs_PVR_TESTING_UTILS": ["services/server/common/tutils.c"],
			"//conditions:default": [],
		})
		#+ select({
		#	":cs_SUPPORT_SECURE_EXPORT": ["services/server/env/linux/ossecure_export.c"],
		#	"//conditions:default": [],
		#})
		+ select({
		    ":cs_PVRSRV_ANDROID_TRACE_GPU_FREQ": ["services/server/env/linux/pvr_gpufreq.c"],
			"//conditions:default": ["services/server/env/linux/pvr_gpufreq.c"],
		})
		+ select({
			":cs_PVRSRV_ENABLE_DYNAMIC_PHYSHEAPS": FILES_PVRSRV_ENABLE_DYNAMIC_PHYSHEAPS,
			"//conditions:default": [],
		})
		+ select({
			":cs_SUPPORT_WRAP_EXTMEM": FILES_SUPPORT_WRAP_EXTMEM,
			"//conditions:default": [],
		})
		+ select({

			":cs_SUPPORT_PHYSMEM_TEST": ["services/server/env/linux/physmem_test.c"],
			"//conditions:default": ["services/server/env/linux/physmem_test.c"],
		})
		+ select({
			":cs_SUPPORT_RGX_and_SUPPORT_RGXKICKSYNC_BRIDGE": ["services/server/devices/rgxkicksync.c"],
			"//conditions:default": ["services/server/devices/rgxkicksync.c"],
		})
		+ select({
			":cs_SUPPORT_RGX_and_SUPPORT_USC_BREAKPOINT": ["services/server/devices/rgxbreakpoint.c"],
			"//conditions:default": ["services/server/devices/rgxbreakpoint.c"],
		})
		+ select({
			":cs_SUPPORT_RGX_and_SUPPORT_PDVFS": ["services/server/devices/rgxpdvfs.c"],
			"//conditions:default": [],
		})
		+ select({
            #":cs_SUPPORT_RGX": ["services/server/devices/rgxfwutils.c"],
            ":cs_SUPPORT_RGX": FILES_SUPPORT_RGX,

			"//conditions:default": [],
		})
		+ select({
		":cs_SUPPORT_WORKLOAD_ESTIMATION": ["services/server/devices/rgxworkest.c"],
			"//conditions:default": [],
		})
		+ select({
			":cs_SUPPORT_VALIDATION_and_PVR_TESTING_UTILS": ["services/server/devices/rgxgpumap.c"],
			"//conditions:default": [],
		}),
	out = "pvrsrvkm.ko",
	copts = ["-include",
			 "$(location //vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691:config_kernel_h)"]
			 + COPTS_MTK,
			 
	header_deps = [
        "//kernel_device_modules-{}/drivers/gpu/mediatek/ged:ged_public_headers".format(kernel_version),
		"//kernel_device_modules-{}/drivers/gpu/mediatek/gpufreq:mtk_gpufreq_headers".format(kernel_version),
		"//kernel_device_modules-{}/drivers/gpu/mediatek/gpufreq/v2:gpufreq_public_headers".format(kernel_version),
		"//kernel_device_modules-{}/drivers/gpu/mediatek/mt-plat:gpu_utility_headers".format(kernel_version),
		"//kernel_device_modules-{}/drivers/gpu/mediatek/gpueb:gpueb_public_headers".format(kernel_version),
    ],
	ko_deps = [
		"//kernel_device_modules-{}/drivers/gpu/mediatek/ged:ged".format(kernel_version),
		"//kernel_device_modules-{}/drivers/gpu/mediatek/gpufreq/v2:mtk_gpufreq_wrapper".format(kernel_version),
		"//kernel_device_modules-{}/drivers/gpu/mediatek/hal:mtk_gpu_hal".format(kernel_version),
		"//kernel_device_modules-{}/drivers/misc/mediatek/irq_monitor:irq_monitor".format(kernel_version),
		"//kernel_device_modules-{}/drivers/gpu/mediatek/gpueb:mtk_gpueb".format(kernel_version),
		"//kernel_device_modules-{}/drivers/soc/mediatek:mtk_tinysys_ipi".format(kernel_version),
	],
    local_defines = select({
			":cs_PVR_ARCH_volcanic": ["PVR_ARCH_VOLCANIC=1"],
			":cs_PVR_ARCH_rogue": ["PVR_ARCH_ROGUE=1"],
            "//conditions:default": ["PVR_ARCH_VOLCANIC=1"],
    }),

	#deps=["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/kernel/drivers/staging/imgtec/tc:tc"],
    conditional_srcs = {
		# Bazel would raise error if files are not existent even if the config
		# is not enable in .config. In some cases, the file is not packaged in
		# the build tarball and need to manually enable/disable below
		# configurations.
#        "CONFIG_X86": {
#            True: ["services/server/env/linux/osfunc_x86.c"],
#        },
#        "CONFIG_ARM": {
#            True: ["services/server/env/linux/osfunc_arm.c"],
#        },
        "CONFIG_ARM64": {
            True: ["services/server/env/linux/osfunc_arm64.c"],
        },
#        "CONFIG_METAG": {
#            True: ["services/server/env/linux/osfunc_metag.c"],
#        },
#        "CONFIG_MIPS": {
#            True: ["services/server/env/linux/osfunc_mips.c"],
#        },
#        "CONFIG_RISCV": {
#            True: ["services/server/env/linux/osfunc_riscv.c"],
#        },
		"CONFIG_PROC_FS": {
			True: ["services/server/env/linux/pvr_procfs.c"],
		},

		# The logic of using PROC_FS and DEBUG_FS is different to makefile. No
		# intend to support DEBUG_FS as it is very old and avoid logic confusion
		#"CONFIG_DEBUG_FS": {
		#	True: ["services/server/env/linux/pvr_debugfs.c"],
		#},

		"CONFIG_EVENT_TRACING": {
			True: select({
				":cs_SUPPORT_RGX_and_PVRSRV_ANDROID_TRACE_GPU_WORK_PERIOD": ["services/server/env/linux/pvr_gputrace.c",
																			 "services/server/env/linux/trace_events.c"],
				":cs_SUPPORT_RGX_and_PVRSRV_TRACE_ROGUE_EVENTS": ["services/server/env/linux/pvr_gputrace.c",
																  "services/server/env/linux/trace_events.c"],
				"//conditions:default": ["services/server/env/linux/trace_events.c"],
			})
		},
		"CONFIG_PCI": {
			True: ["services/system/common/env/linux/pci_support.c"],
		},
    },

	# Exported headers
#	hdrs = ["drivers/staging/imgtec/config_kernel.h"],
	hdrs = select({
			":cs_PVR_ARCH_volcanic_and_PVR_SYSTEM_rgx_linux_tc": ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/system/volcanic:rgx_linux_tc_header"],
			":cs_PVR_ARCH_rogue_and_PVR_SYSTEM_rgx_linux_tc": ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/system/rogue:rgx_linux_tc_header"],
#        	"//conditions:default": ["include/img_defs.h"],
	        "//conditions:default": [],
		})
		+ ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/include:include_headers" ]
		+ ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/kernel/drivers/staging/imgtec:imgtec_headers" ]
		+ ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/system/volcanic:private_rgx_linux_tc_headers" ]
		+ ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/system/volcanic:rgx_linux_tc_header" ]
		+ select({
			":cs_PVR_ARCH_volcanic": ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/generated/volcanic:generated_headers"]
								   + ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/include/volcanic:include_headers" ]
								   + ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/hwdefs/volcanic:hwdefs_headers"]
								   + ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/server/devices/volcanic:device_headers"]
								   + ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/include/volcanic:include_headers"]
								   ,
			":cs_PVR_ARCH_rogue": ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/generated/rogue:generated_headers"]
				 				+ ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/include/rogue:include_headers"]
				 				+ ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/hwdefs/rogue:hwdefs_headers"]
								+ ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/server/devices/rogue:device_headers"]
								+ ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/include/rogue:include_headers"]
								,
			"//conditions:default": ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/generated/volcanic:generated_headers"]
								   + ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/include/volcanic:include_headers" ]
								   + ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/hwdefs/volcanic:hwdefs_headers"]
								   + ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/server/devices/volcanic:device_headers"]
								   + ["//vendor/mediatek/kernel_modules/gpu/gpu_rgx/m25.1RTM6715691/services/include/volcanic:include_headers"],
		}),

	includes = select({
				":cs_PVR_ARCH_volcanic": [
					"include/volcanic",
					"include/volcanic/system/rgx_tc",
					"services/system/volcanic/include",
					"services/include/volcanic",
					"services/system/volcanic/rgx_mtk",
					"services/server/devices/volcanic",
					"services/shared/devices/volcanic",
					"hwdefs/volcanic",
					"hwdefs/volcanic/km",
					"drivers/staging/imgtec/pvrsrvkm/volcanic",
					"drivers/staging/imgtec/pvrsrvkm/volcanic/hwdefs",
					"drivers/staging/imgtec/pvrsrvkm/volcanic/hwdefs/km",
					"generated/volcanic/rgxhwperf_bridge",
					"generated/volcanic/cache_bridge",
					"generated/volcanic/devicememhistory_bridge",
					"generated/volcanic/dma_bridge",
					"generated/volcanic/cmm_bridge",
					"generated/volcanic/htbuffer_bridge",
					"generated/volcanic/di_bridge",
					"generated/volcanic/mmextmem_bridge",
					"generated/volcanic/pdumpctrl_bridge",
					"generated/volcanic/pvrtl_bridge",
					"generated/volcanic/rgxcmp_bridge",
					"generated/volcanic/gxhwperf_bridge",
					"generated/volcanic/rgxpdump_bridge",
					"generated/volcanic/rgxta3d_bridge",
					"generated/volcanic/rgxtq2_bridge",
					"generated/volcanic/ri_bridge",
					"generated/volcanic/sync_bridge",
					"generated/volcanic/dmabuf_bridge",
					"generated/volcanic/mm_bridge",
					"generated/volcanic/pdump_bridge",
					"generated/volcanic/pdumpmm_bridge",
					"generated/volcanic/rgxbreakpoint_bridge",
					"generated/volcanic/rgxfwdbg_bridge",
					"generated/volcanic/rgxkicksync_bridge",
					"generated/volcanic/rgxray_bridge",
					"generated/volcanic/rgxregconfig_bridge",
					"generated/volcanic/rgxtimerquery_bridge",
					"generated/volcanic/rgxtq_bridge",
					"generated/volcanic/srvcore_bridge",
					"generated/volcanic/synctracking_bridge",
				],

				":cs_PVR_ARCH_rogue": [
					"include/rogue",
					"include/rogue/system/rgx_tc",
					"services/system/rogue/include",
					"services/include/rogue",
					"services/system/rogue/rgx_mtk",
					"services/server/devices/rogue",
					"services/shared/devices/rogue",
					"hwdefs/rogue",
					"hwdefs/rogue/km",
					"drivers/staging/imgtec/pvrsrvkm/rogue",
					"drivers/staging/imgtec/pvrsrvkm/rogue/hwdefs",
					"drivers/staging/imgtec/pvrsrvkm/rogue/hwdefs/km",
					"generated/rogue/rgxhwperf_bridge",
					"generated/rogue/cache_bridge",
					"generated/rogue/devicememhistory_bridge",
					"generated/rogue/dma_bridge",
					"generated/rogue/cmm_bridge",
					"generated/rogue/htbuffer_bridge",
					"generated/rogue/di_bridge",
					"generated/rogue/mmextmem_bridge",
					"generated/rogue/pdumpctrl_bridge",
					"generated/rogue/pvrtl_bridge",
					"generated/rogue/rgxcmp_bridge",
					"generated/rogue/gxhwperf_bridge",
					"generated/rogue/rgxpdump_bridge",
					"generated/rogue/rgxta3d_bridge",
					"generated/rogue/rgxtq2_bridge",
					"generated/rogue/ri_bridge",
					"generated/rogue/sync_bridge",
					"generated/rogue/dmabuf_bridge",
					"generated/rogue/mm_bridge",
					"generated/rogue/pdump_bridge",
					"generated/rogue/pdumpmm_bridge",
					"generated/rogue/rgxbreakpoint_bridge",
					"generated/rogue/rgxfwdbg_bridge",
					"generated/rogue/rgxkicksync_bridge",
					"generated/rogue/rgxray_bridge",
					"generated/rogue/rgxregconfig_bridge",
					"generated/rogue/rgxtimerquery_bridge",
					"generated/rogue/rgxtq_bridge",
					"generated/rogue/srvcore_bridge",
					"generated/rogue/synctracking_bridge",
					],
				"//conditions:default": [
					"include/volcanic",
					"include/volcanic/system/rgx_tc",
					"services/system/volcanic/include",
					"services/include/volcanic",
					"services/system/volcanic/rgx_mtk",
					"services/system/volcanic/rgx_mtk/mt6855",
					"services/server/devices/volcanic",
					"services/shared/devices/volcanic",
					"hwdefs/volcanic",
					"hwdefs/volcanic/km",
					"drivers/staging/imgtec/pvrsrvkm/volcanic",
					"drivers/staging/imgtec/pvrsrvkm/volcanic/hwdefs",
					"drivers/staging/imgtec/pvrsrvkm/volcanic/hwdefs/km",
					"generated/volcanic/rgxhwperf_bridge",
					"generated/volcanic/cache_bridge",
					"generated/volcanic/devicememhistory_bridge",
					"generated/volcanic/dma_bridge",
					"generated/volcanic/cmm_bridge",
					"generated/volcanic/htbuffer_bridge",
					"generated/volcanic/di_bridge",
					"generated/volcanic/mmextmem_bridge",
					"generated/volcanic/pdumpctrl_bridge",
					"generated/volcanic/pvrtl_bridge",
					"generated/volcanic/rgxcmp_bridge",
					"generated/volcanic/gxhwperf_bridge",
					"generated/volcanic/rgxpdump_bridge",
					"generated/volcanic/rgxta3d_bridge",
					"generated/volcanic/rgxtq2_bridge",
					"generated/volcanic/ri_bridge",
					"generated/volcanic/sync_bridge",
					"generated/volcanic/dmabuf_bridge",
					"generated/volcanic/mm_bridge",
					"generated/volcanic/pdump_bridge",
					"generated/volcanic/pdumpmm_bridge",
					"generated/volcanic/rgxbreakpoint_bridge",
					"generated/volcanic/rgxfwdbg_bridge",
					"generated/volcanic/rgxkicksync_bridge",
					"generated/volcanic/rgxray_bridge",
					"generated/volcanic/rgxregconfig_bridge",
					"generated/volcanic/rgxtimerquery_bridge",
					"generated/volcanic/rgxtq_bridge",
					"generated/volcanic/srvcore_bridge",
					"generated/volcanic/synctracking_bridge",
				],
				})
			+ [
                "include",
				"include/system",
				"include/system/rgx_tc",
				"include/public",
				"include/drm",
				"services/server",
				"services/server/env/linux",
				"services/server/include",
				"services/system/include",
				"services/shared/include",
				"services/include",
				"services/server/devices",
				"services/server/common",
				"services/shared/common",
				"drivers/staging/imgtec",
				#"drivers/staging/imgtec/tc",
				"drivers/staging/imgtec/pvrsrvkm",
            ],
)
