export MTK_PLATFORM_VERSION := mt6993

obj-m += mali_avalon/a16w/drivers/gpu/arm/midgard/
obj-m += mali_avalon/a16w/drivers/base/arm/memory_group_manager/
obj-m += mali_avalon/a16w/drivers/base/arm/protected_memory_allocator/
obj-m += mali_avalon/a16w/drivers/base/arm/dma_buf_test_exporter/

obj-m += mali_avalon/a16w_porting/drivers/gpu/arm/midgard/
obj-m += mali_avalon/a16w_porting/drivers/base/arm/memory_group_manager/
obj-m += mali_avalon/a16w_porting/drivers/base/arm/protected_memory_allocator/
obj-m += mali_avalon/a16w_porting/drivers/base/arm/dma_buf_test_exporter/

