--- drivers/gpu/arm/midgard/Kbuild
+++ drivers/gpu/arm/midgard/Kbuild
@@ -143,9 +151,7 @@
 # Kernel Modules
 #
 obj-$(CONFIG_MALI_MIDGARD) += mali_kbase.o
-ifeq ($(CONFIG_MALI_ARBITRATION),y)
 obj-$(CONFIG_MALI_ARBITRATION) += arbitration/
-endif
 obj-$(CONFIG_MALI_KUTF)    += tests/
 
 mali_kbase-y := \
