export MTK_PLATFORM_VERSION := mt6893

obj-m += mali_valhall/mali-r32p1/drivers/gpu/arm/midgard/
obj-m += mali_valhall/mali-r32p1/drivers/base/arm/memory_group_manager/
obj-m += mali_valhall/mali-r32p1/drivers/base/arm/protected_memory_allocator/