include $(src)/Kbuild-mtk-custom-env

curr := platform/mtk_platform_common

mali_kbase-y += $(curr)/mtk_platform_common.o
ifeq ($(CONFIG_MALI_MTK_DEVFREQ_GOVERNOR),y)
    mali_kbase-y += $(curr)/mtk_platform_dvfs.o
endif ## CONFIG_MALI_MTK_DEVFREQ_GOVERNOR ##
ccflags-y += -I$(srctree)/drivers/devfreq/
ccflags-y += -Wno-unused-variable
